name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  bats:
    name: Unit Tests (bats)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run tests
        run: ./tests/bats/bin/bats --formatter tap tests/unit/
